Repository WildCodeSchool/orleans-php-202009-project-paradis-ptits-cracks, pull requests merged in 2020-11, with the labels that each got.

#66 admin - list the dogs
  public/assets/css/admindog.css
  src/Controller/AdminDogController.php
  src/Model/DogManager.php
  src/View/Admin/list_dog.html.twig
Labels: Reviewed

#67 fix add dog functionality
  petitscracks_db.sql
  src/Controller/AdminDogController.php
  src/View/Admin/add_dog.html.twig
Labels: Corrections done, Reviewed

#74 add ifempty on the validation of link to CDF to make it nullable
  src/Controller/AdminDogController.php
Labels: Reviewed

#76 S16 coordonnées
  public/assets/css/contact.css
  public/assets/css/style.css
  public/assets/images/call.png
  public/assets/images/dog-and-man.png
  public/assets/images/facebook.png
  public/assets/images/home.png
  public/assets/images/mail.png
  public/assets/images/pawprint.png
  src/Controller/ContactController.php
  src/View/Contact/contact.html.twig
  src/View/include/_footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#77 add list actu admin
  petitscracks_db.sql
  public/assets/css/adminactuality.css
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/list_actuality.html.twig
  src/View/Admin/list_dog.html.twig
Labels: Reviewed

#81 US05_created selectbyid page admin
  public/assets/css/admindog.css
  src/Controller/AdminDogController.php
  src/Model/DogManager.php
  src/View/Admin/list_dog.html.twig
  src/View/Admin/show_dog.html.twig
Labels: Reviewed

#73 S013 raiser description
  public/assets/css/breeding.css
  public/assets/css/style.css
  public/assets/images/bottom-background1.png
  public/assets/images/breeding_photo.jpg
  public/assets/images/carousel_photo1.jpg
  public/assets/images/carousel_photo2.jpg
  public/assets/images/carousel_photo3.jpg
  public/assets/images/club_banner.jpg
  public/assets/images/dog-pat-arrow-next.png
  public/assets/images/dog-pat-arrow-prev.png
  public/assets/images/dog_raiser.jpg
  public/assets/images/top-background1.png
  src/Controller/BreedingController.php
  src/View/Breeding/breeding.html.twig
Labels: Corrections done, Reviewed

#82 Us06 s01 create form add actuality admin
  public/assets/css/adminactuality.css
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/add_actuality.html.twig
  src/View/Admin/list_actuality.html.twig
Labels: Reviewed

#85 US03 add edit dog functionality on admin
  src/Controller/AdminDogController.php
  src/Model/DogManager.php
  src/View/Admin/edit_dog.html.twig
Labels: Reviewed

#86 fixUS02_improve navigation for add
  src/Controller/AdminDogController.php
  src/View/Admin/list_dog.html.twig
Labels: Reviewed

#87 US32_create navbar for admin
  composer.json
  composer.lock
  grumphp.yml
  public/assets/css/adminNavBar.css
  public/assets/css/admindog.css
  src/View/Admin/add_dog.html.twig
  src/View/Admin/edit_dog.html.twig
  src/View/Admin/list_dog.html.twig
  src/View/Admin/show_dog.html.twig
  src/View/include/_adminNavBar.html.twig
Labels: Reviewed

#84 US04_add the delete functionality on admin for dogs
  src/Controller/AdminDogController.php
  src/Model/DogManager.php
  src/View/Admin/list_dog.html.twig
  src/View/Admin/show_dog.html.twig
Labels: Conflicts, Corrections done, Reviewed

#91 fixe view form add actuality admin
  src/Controller/AdminActualityController.php
  src/View/Admin/add_actuality.html.twig
Labels: Reviewed

#80 Us 20 dog page
  composer.lock
  public/assets/css/dog_General.css
  public/assets/css/navBar.css
  src/Controller/AdminDogController.php
  src/Controller/DogController.php
  src/Model/DogManager.php
  src/View/Dog/card.html.twig
  src/View/Dog/index.html.twig
  src/View/include/_navBar.html.twig
Labels: Corrections done, Reviewed

#109 maj onglet pour redirection au niveau des pages
  src/View/include/_navBar.html.twig
Labels: Reviewed

#110 fix au niveu du responsive de la page dog + centrage de la navbar
  public/assets/css/dog_General.css
  src/Controller/ActualityController.php
  src/View/Actuality/index.html.twig
  src/View/Actuality/show.html.twig
  src/View/Dog/card.html.twig
  src/View/Dog/index.html.twig
  src/View/include/_navBar.html.twig
Labels: Corrections done, Reviewed

#115 S03 us33 homepage
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/header_background.jpg
  public/assets/images/petits-crack_actu-default.jpg
  src/Controller/HomeController.php
  src/Model/ActualityManager.php
  src/Model/DogManager.php
  src/View/Home/index.html.twig
Labels: Reviewed

#120 US3_fix_footer_css
  src/View/include/_footer.html.twig
Labels: Reviewed

#121 S03 fix navbar color and home link
  public/assets/css/navBar.css
  src/View/include/_navBar.html.twig
Labels: Reviewed

#117 Us07 create form modify actuality
  public/assets/css/adminactuality.css
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/add_actuality.html.twig
  src/View/Admin/edit_actuality.html.twig
  src/View/Admin/list_actuality.html.twig
  src/View/Admin/show_actuality.html.twig
Labels: Corrections done

#119 Us18 form contact
  public/assets/css/contact.css
  public/assets/css/style.css
  src/View/Contact/contact.html.twig
Labels: Reviewed

#123 S03 us08 create button delete
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/show_actuality.html.twig
Labels: Reviewed

#124 add button for add actuality and add <th> Action
  src/View/Admin/list_actuality.html.twig
Labels: Reviewed

#125 Us34 fix legal css
  public/assets/css/legal.css
  public/assets/css/style.css
  src/View/Legal/legal.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#126 Dev to master
  public/assets/css/legal.css
  public/assets/css/style.css
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/list_actuality.html.twig
  src/View/Admin/show_actuality.html.twig
  src/View/Legal/legal.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#141 show actuality
  public/assets/css/actuality.css
  src/View/Actuality/cardActuality.html.twig
  src/View/Actuality/show.html.twig
Labels: Reviewed

#143 S04 us35 add pictures
  public/uploads/.gitignore
  src/Controller/AdminDogController.php
  src/View/Admin/add_dog.html.twig
  src/View/Admin/show_dog.html.twig
  src/View/Dog/card.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#144 fix home link display in burger menu
  src/View/include/_navBar.html.twig
Labels: Reviewed

#146 update form add actuality
  src/View/Admin/add_actuality.html.twig
Labels: Reviewed

#154 S04 us36 edit pictures
  src/Controller/AdminDogController.php
  src/View/Admin/edit_dog.html.twig
Labels: Reviewed

#137 fix img dog
  public/assets/css/dog_General.css
  src/View/Dog/card.html.twig
  src/View/Dog/index.html.twig
Labels: Corrections done, Reviewed

#151 S04 us37 admin home
  public/assets/css/admindog.css
  src/Controller/AdminController.php
  src/Model/DogManager.php
  src/View/Admin/admin_index.html.twig
  src/View/include/_adminNavBar.html.twig
Labels: Reviewed

#156 dev to master
  public/assets/css/actuality.css
  public/assets/css/admindog.css
  public/assets/css/dog_General.css
  public/uploads/.gitignore
  src/Controller/AdminActualityController.php
  src/Controller/AdminController.php
  src/Controller/AdminDogController.php
  src/Model/ActualityManager.php
  src/Model/DogManager.php
  src/View/Actuality/cardActuality.html.twig
  src/View/Actuality/index.html.twig
  src/View/Actuality/show.html.twig
  src/View/Admin/add_actuality.html.twig
  src/View/Admin/add_dog.html.twig
  src/View/Admin/admin_index.html.twig
  src/View/Admin/edit_dog.html.twig
  src/View/Admin/show_actuality.html.twig
  src/View/Admin/show_dog.html.twig
  src/View/Dog/card.html.twig
  src/View/Dog/index.html.twig
  src/View/Home/index.html.twig
  src/View/include/_adminNavBar.html.twig
  src/View/include/_navBar.html.twig
Labels: Reviewed

#158 Us10 mettre à jour le form edit actuality
  src/Controller/AdminActualityController.php
  src/Model/ActualityManager.php
  src/View/Admin/add_actuality.html.twig
  src/View/Admin/edit_actuality.html.twig
Labels: Reviewed

#159 S05 us38 choose homepage dogs
  src/Controller/HomeController.php
  src/Model/DogManager.php
  src/View/Admin/add_dog.html.twig
  src/View/Admin/edit_dog.html.twig
  src/View/Admin/list_dog.html.twig
  src/View/Admin/show_dog.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#160 FIX_replace select * by precise requests to avoid bugs
  src/Model/DogManager.php
Labels: Reviewed

#161 FIX links in admin homepage
  src/View/Admin/admin_index.html.twig
Labels: Reviewed

#153 S21 dogs individual detail
  public/assets/css/dogShow.css
  public/assets/css/style.css
  public/assets/images/unknown_dog.jpeg
  src/Controller/DogController.php
  src/View/Dog/show.html.twig
Labels: Corrections done, Reviewed

#157 Us18 mailer
  composer.json
  composer.lock
  config/db.php.dist
  src/Controller/ContactController.php
  src/View/Contact/contact.html.twig
  src/View/Contact/email.html.twig
Labels: Corrections done, Reviewed

#162 Fixfooter
  public/assets/css/contact.css
  public/assets/css/footer.css
Labels: Reviewed

#163 dev to master
  composer.json
  composer.lock
  config/db.php.dist
  public/assets/css/contact.css
  public/assets/css/dogShow.css
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/unknown_dog.jpeg
  src/Controller/AdminActualityController.php
  src/Controller/ContactController.php
  src/Controller/DogController.php
  src/Controller/HomeController.php
  src/Model/ActualityManager.php
  src/Model/DogManager.php
  src/View/Admin/add_actuality.html.twig
  src/View/Admin/add_dog.html.twig
  src/View/Admin/admin_index.html.twig
  src/View/Admin/edit_actuality.html.twig
  src/View/Admin/edit_dog.html.twig
  src/View/Admin/list_dog.html.twig
  src/View/Admin/show_dog.html.twig
  src/View/Contact/contact.html.twig
  src/View/Contact/email.html.twig
  src/View/Dog/show.html.twig
  src/View/Home/index.html.twig
Labels: Reviewed

#189 fix titre admin actu
  public/assets/css/adminactuality.css
Labels: Reviewed

#193 Fix contact
  src/View/Contact/contact.html.twig
Labels: Reviewed

#194 fix upload Actuality
  src/View/Actuality/cardActuality.html.twig
  src/View/Actuality/show.html.twig
Labels: Reviewed

#195 fix upload dog + css title
  public/assets/css/dog_General.css
  src/View/Dog/card.html.twig
  src/View/Dog/index.html.twig
  src/View/Dog/show.html.twig
Labels: Reviewed

#197 Fix admin index
  public/assets/css/admindog.css
  src/Model/DogManager.php
  src/View/Admin/admin_index.html.twig
Labels: Reviewed

#198 FIX_AdminNavbar wrong link on logo in responsive
  src/View/include/_adminNavBar.html.twig
Labels: Reviewed

#164 Fix width female dog section
  public/assets/css/dog_General.css
  src/View/Dog/index.html.twig
Labels: Reviewed

#196 Fix form
  public/assets/css/contact.css
  src/View/Contact/contact.html.twig
Labels: Reviewed

#199 Fix legal
  src/View/Legal/legal.html.twig
Labels: Reviewed

#200 Fix update dog
  src/Controller/AdminDogController.php
  src/Model/DogManager.php
  src/View/Admin/add_dog.html.twig
  src/View/Admin/edit_dog.html.twig
Labels: Reviewed

#201 FIX-Center dog name on admin/show
  src/View/Admin/show_dog.html.twig
Labels: Reviewed

#202 FIX footer for W3C on home
  src/View/include/_footer.html.twig
Labels: Reviewed

#203 Fix homepage
  public/assets/css/home.css
  public/assets/css/style.css
  src/Model/ActualityManager.php
  src/View/Home/index.html.twig
Labels: Reviewed

#206 FIX_Style-dog-show
  public/assets/css/dogShow.css
  src/Controller/DogController.php
  src/View/Dog/show.html.twig
Labels: Reviewed

#207 FIX_add style on actuality
  public/assets/css/actuality-show.css
  src/View/Actuality/index.html.twig
  src/View/Actuality/show.html.twig
Labels: Reviewed

#204 Fix dog index
  public/assets/css/dog_General.css
  src/Model/DogManager.php
  src/View/Dog/card.html.twig
  src/View/Dog/index.html.twig
Labels: Conflicts, Corrections done

#210 FIX_default background light instead of white
  public/assets/css/style.css
Labels: Reviewed

#208 Fix imagesactuality index
  public/assets/css/actuality.css
  src/View/Actuality/cardActuality.html.twig
  src/View/Actuality/index.html.twig
Labels: Corrections done, Reviewed

#211 Fix raiser description
  public/assets/css/breeding.css
  public/assets/images/background-carousel.jpg
  src/View/Breeding/breeding.html.twig
Labels: Reviewed

#209 dev->master
  public/assets/css/actuality-show.css
  public/assets/css/actuality.css
  public/assets/css/adminactuality.css
  public/assets/css/admindog.css
  public/assets/css/breeding.css
  public/assets/css/contact.css
  public/assets/css/dogShow.css
  public/assets/css/dog_General.css
  public/assets/css/home.css
  public/assets/css/style.css
  public/assets/images/background-carousel.jpg
  src/Controller/AdminDogController.php
  src/Controller/DogController.php
  src/Model/ActualityManager.php
  src/Model/DogManager.php
  src/View/Actuality/cardActuality.html.twig
  src/View/Actuality/index.html.twig
  src/View/Actuality/show.html.twig
  src/View/Admin/add_dog.html.twig
  src/View/Admin/admin_index.html.twig
  src/View/Admin/edit_dog.html.twig
  src/View/Admin/show_dog.html.twig
  src/View/Breeding/breeding.html.twig
  src/View/Contact/contact.html.twig
  src/View/Dog/card.html.twig
  src/View/Dog/index.html.twig
  src/View/Dog/show.html.twig
  src/View/Home/index.html.twig
  src/View/Legal/legal.html.twig
  src/View/include/_adminNavBar.html.twig
  src/View/include/_footer.html.twig
Labels: Reviewed

#212 FIX_border top on table
  public/assets/css/dogShow.css
Labels: Reviewed

#214 Fix breeding spacings
  public/assets/css/breeding.css
  src/View/Breeding/breeding.html.twig
Labels: Reviewed

#215 dev->master
  public/assets/css/breeding.css
  public/assets/css/dogShow.css
  src/View/Breeding/breeding.html.twig
Labels: Reviewed
